server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: 192.168.91.129
      port: 6380