server:
  port: 8511

spring:
  # Redis的相关配置
  data:
    redis:
      host: 192.168.91.129
      port: 6380
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.91.129:3304/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 20040512

mybatis:
  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:/mapper/*/*.xml
  mapper-locations: classpath:/mapper/*.xml